# Generated by Django 2.1.15 on 2020-11-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu_Dien_Tu_App', '0002_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
