# Generated by Django 2.1.15 on 2020-12-01 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu_Dien_Tu_App', '0003_table_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescribeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.CharField(max_length=1000)),
                ('menuItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu_Dien_Tu_App.MenuItem')),
            ],
        ),
    ]
