# Generated by Django 2.1.15 on 2020-12-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu_Dien_Tu_App', '0004_describeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
