# Generated by Django 2.1.15 on 2020-12-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu_Dien_Tu_App', '0005_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='describe',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
