# Generated by Django 2.1.15 on 2020-12-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu_Dien_Tu_App', '0009_auto_20201217_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
