# Generated by Django 2.1.15 on 2020-12-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu_Dien_Tu_App', '0010_menuitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=20)),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
    ]
